//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EloBuddy.SDK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EloBuddy.SDK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Colors&quot;: 
        ///    {
        ///        &quot;Scrollbar&quot;:  { &quot;A&quot;: 200, &quot;R&quot;: 100, &quot;G&quot;: 100, &quot;B&quot;: 100 },
        ///        &quot;ScrollbarBackground&quot;:  { &quot;A&quot;: 255, &quot;R&quot;: 0, &quot;G&quot;: 0, &quot;B&quot;: 0 }
        ///    },
        ///    &quot;SpriteAtlas&quot;: 
        ///    {
        ///        &quot;MainForm&quot;: 
        ///        {
        ///            &quot;Complete&quot;: 
        ///            {
        ///                &quot;X&quot;: 0,
        ///                &quot;Y&quot;: 0,
        ///                &quot;Width&quot;: 758,
        ///                &quot;Height&quot;: 598
        ///            },
        ///            &quot;Header&quot;: 
        ///            {
        ///                &quot;X&quot;: 0,
        ///                &quot;Y&quot;: 0,
        ///                &quot;Width&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;ChampName&quot;: &quot;Aatrox&quot;,
        ///        &quot;SpellSlot&quot;: &quot;Q&quot;,
        ///        &quot;SpellName&quot;: &quot;aatroxq&quot;,
        ///        &quot;SkillType&quot;: &quot;Skillshot&quot;
        ///    },
        ///    {
        ///        &quot;ChampName&quot;: &quot;Akali&quot;,
        ///        &quot;SpellSlot&quot;: &quot;R&quot;,
        ///        &quot;SpellName&quot;: &quot;akalishadowdance&quot;,
        ///        &quot;SkillType&quot;: &quot;Targeted&quot;
        ///    },
        ///    {
        ///        &quot;ChampName&quot;: &quot;Alistar&quot;,
        ///        &quot;SpellSlot&quot;: &quot;W&quot;,
        ///        &quot;SpellName&quot;: &quot;headbutt&quot;,
        ///        &quot;SkillType&quot;: &quot;Targeted&quot;
        ///    },
        ///    {
        ///        &quot;ChampName&quot;: &quot;Corki&quot;,
        ///        &quot;SpellSlot&quot;: &quot;W&quot;,
        ///        &quot;Spel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Gapclosers {
            get {
                return ResourceManager.GetString("Gapclosers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Gill_Sans_MT_Light {
            get {
                object obj = ResourceManager.GetObject("Gill_Sans_MT_Light", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Gill_Sans_MT_Pro_Book {
            get {
                object obj = ResourceManager.GetObject("Gill_Sans_MT_Pro_Book", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Gill_Sans_MT_Pro_Medium {
            get {
                object obj = ResourceManager.GetObject("Gill_Sans_MT_Pro_Medium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///   &quot;1001&quot;:{
        ///      &quot;name&quot;:&quot;Boots of Speed&quot;,
        ///      &quot;group&quot;:&quot;BootsNormal&quot;,
        ///      &quot;description&quot;:&quot;&lt;groupLimit&gt;Limited to 1.&lt;/groupLimit&gt;&lt;br&gt;&lt;br&gt;&lt;unique&gt;UNIQUE Passive - Enhanced Movement:&lt;/unique&gt; +25 Movement Speed&quot;,
        ///      &quot;colloq&quot;:&quot;;&quot;,
        ///      &quot;plaintext&quot;:&quot;Slightly increases Movement Speed&quot;,
        ///      &quot;into&quot;:[
        ///         &quot;3006&quot;,
        ///         &quot;3047&quot;,
        ///         &quot;3020&quot;,
        ///         &quot;3158&quot;,
        ///         &quot;3111&quot;,
        ///         &quot;3117&quot;,
        ///         &quot;3009&quot;
        ///      ],
        ///      &quot;image&quot;:{
        ///         &quot;full&quot;:&quot;1001.png&quot;,
        ///         &quot;sprite&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemData {
            get {
                return ResourceManager.GetString("ItemData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Aatrox&quot;: 2,
        ///    &quot;Ahri&quot;: 4,
        ///    &quot;Akali&quot;: 3,
        ///    &quot;Alistar&quot;: 1,
        ///    &quot;Amumu&quot;: 1,
        ///    &quot;Anivia&quot;: 4,
        ///    &quot;Annie&quot;: 4,
        ///    &quot;Ashe&quot;: 4,
        ///    &quot;Azir&quot;: 4,
        ///    &quot;Bard&quot;: 1,
        ///    &quot;Blitzcrank&quot;: 1,
        ///    &quot;Brand&quot;: 4,
        ///    &quot;Braum&quot;: 1,
        ///    &quot;Caitlyn&quot;: 4,
        ///    &quot;Cassiopeia&quot;: 4,
        ///    &quot;Chogath&quot;: 2,
        ///    &quot;Corki&quot;: 4,
        ///    &quot;Darius&quot;: 2,
        ///    &quot;Diana&quot;: 3,
        ///    &quot;Draven&quot;: 4,
        ///    &quot;DrMundo&quot;: 1,
        ///    &quot;Ekko&quot;: 4,
        ///    &quot;Elise&quot;: 2,
        ///    &quot;Evelynn&quot;: 2,
        ///    &quot;Ezreal&quot;: 4,
        ///    &quot;FiddleSticks&quot;: 3,
        ///    &quot;Fiora&quot;: 3,
        ///    &quot;Fizz&quot;: 3,
        ///    &quot;Ga [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Priorities {
            get {
                return ResourceManager.GetString("Priorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SimpleNotification {
            get {
                object obj = ResourceManager.GetObject("SimpleNotification", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Theme {
            get {
                object obj = ResourceManager.GetObject("Theme", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
