#include "Stdafx.h"
#pragma once

namespace EloBuddy
{
	public enum class PacketChannel
	{
		Handshake,
		C2S,
		GamePlay,
		S2C,
		LowPriority,
		Communication,
		LoadingScreen
	};

	public enum class PacketProtocolFlags
	{
		Reliable,
		NoFlags,
		Unsequenced
	};

	public enum class GameObjectOrder
	{
		HoldPosition = 1,
		MoveTo,
		AttackUnit,
		AutoAttackPet,
		AutoAttack,
		MovePet,
		AttackTo,
		Stop = 10
	};

	public enum class GameType
	{
		Normal,
		Dominion,
		Tutorial,
		ARAM,
		FirstBlood,
		Ascension,
		KingPoro
	};

	public enum class SpellSlot
	{
		Unknown = -1,
		Q,
		W,
		E,
		R,
		Summoner1,
		Summoner2,
		Item1,
		Item2,
		Item3,
		Item4,
		Item5,
		Item6,
		Trinket,
		Recall,
		OathSworn = 92,
		CapturePoint = 94,
		Internal = 10000
	};

	public enum class SpellState
	{
		Ready = 0,
		NotAvailable = 4,
		Surpressed = 8,
		NotLearned = 12,
		Disabled = 24,
		Cooldown = 32,
		NoMana = 96,
		Unknown
	};

	[System::FlagsAttribute]
	public enum class SpellStateFlags
	{
		Ready = 0,
		NotLearned = 1 << 2,
		Supressed = 1 << 3,
		Cooldown = 1 << 5,
		NoMana = 1 << 6
	};

	[System::FlagsAttribute]
	public enum class SpellDataFlags : uint
	{
		Autocast = 2u,
		Instacast = 4u,
		PersistThroughDeath = 8u,
		NonDispellable = 16u,
		AffectImportantBotTargets = 64u,
		AllowWhileTaunted = 128u,
		NotAffectZombie = 256u,
		AffectUntargetable = 512u,
		AffectEnemies = 1024u,
		AffectFriends = 2048u,
		AffectBuildings = 4096u,
		NotAffectSelf = 8192u,
		AffectNeutral = 16384u,
		AffectMinions = 32768u,
		AffectHeroes = 65536u,
		AffectTurrets = 131072u,
		AlwaysSelf = 262144u,
		AffectDead = 524288u,
		AffectNotPet = 1048576u,
		AffectBarrackOnly = 2097152u,
		AffectWards = 67108864u,
		AffectUseable = 134217728u
	};

	[System::FlagsAttribute]
	public enum class SpellFlags
	{
		Autocast = 2,
		Instacast = 4,
		PersistThroughDeath = 8,
		NonDispellable = 16,
		AffectImportantBotTargets = 64,
		AllowWhileTaunted = 128,
		AffectUntargetable = 512,
		AffectEnemies = 1024,
		AffectFriends = 2048,
		AffectBuildings = 4096,
		NotAffectSelf = 8192,
		AffectNeutral = 16384,
		AffectMinions = 32768,
		AffectHeroes = 65536,
		AffectTurrets = 131072,
		AlwaysSelf = 262144,
		AffectDead = 524288,
		AffectNotPet = 1048576,
		AffectBarrackOnly = 2097152,
		NonTargetableAlly = 8388608
	};

	public enum class SpellDataTargetType
	{
		Self,
		Unit,
		LocationAoe,
		Cone,
		SelfAoe,
		Location = 6,
		SelfAndUnit = 5,
		Location2 = 7,
		LocationVector,
		LocationSummon = 10,
		Location3,
		LocationTunnel
	};

	public enum class BuffType
	{
		Internal,
		Aura,
		CombatEnchancer,
		CombatDehancer,
		SpellShield,
		Stun,
		Invisibility,
		Silence,
		Taunt,
		Polymorph,
		Slow,
		Snare,
		Damage,
		Heal,
		Haste,
		SpellImmunity,
		PhysicalImmunity,
		Invulnerability,
		Sleep,
		NearSight,
		Frenzy,
		Fear,
		Charm,
		Poison,
		Suppression,
		Blind,
		Counter,
		Shred,
		Flee,
		Knockup,
		Knockback,
		Disarm
	};

	public enum class GameMode
	{
		Connecting = 1,
		Running,
		Paused,
		Finished,
		Exiting
	};

	[System::FlagsAttribute]
	public enum class CollisionFlags : ushort
	{
		None = 0,
		Grass = 1,
		Wall = 2,
		Building = 64,
		Prop = 128,
		GlobalVision = 256,
	};

	public enum class GameObjectTeam
	{
		Unknown,
		Order = 100,
		Chaos = 200,
		Neutral = 300
	};

	public enum class GameObjectCombatType
	{
		Melee = 1,
		Ranged
	};

	[System::FlagsAttribute]
	public enum class GameObjectCharacterState
	{
        CanAttack = 1,
        CanCast = 2,
        CanMove = 4,
        Immovable = 8,
        IsStealth = 16,
        RevealSpecificUnit = 32,
        Taunted = 64,
        Feared = 128,
        Fleeing = 256,
        Surpressed = 512,
        Asleep = 1024,
        NearSight = 2048,
        Ghosted = 4096,
        GhostProof = 8192,
        Charmed = 16384,
        NoRender = 32768,
        DodgePiercing = 131072,
        DisableAmbientGold = 262144,
        DisableAmbientXP = 524288,
        ForceRenderParticles = 65536
	};

	public enum class GameObjectType
	{
		NeutralMinionCamp,
		obj_AI_Base,
		FollowerObject,
		FollowerObjectWithLerpMovement,
		AIHeroClient,
		obj_AI_Marker,
		obj_AI_Minion,
		LevelPropAI,
		obj_AI_Turret,
		obj_GeneralParticleEmitter,
		MissileClient,
		DrawFX,
		UnrevealedTarget,
		obj_LampBulb,
		obj_Barracks,
		obj_BarracksDampener,
		obj_AnimatedBuilding,
		obj_Building,
		obj_Levelsizer,
		obj_NavPoint,
		obj_SpawnPoint,
		obj_Lake,
		obj_HQ,
		obj_InfoPoint,
		LevelPropGameObject,
		LevelPropSpawnerPoint,
		obj_Shop,
		obj_Turret,
		GrassObject,
		obj_Ward,
		GameObject,
		Unknown
	};

	public enum class GameEventId
	{
		OnDelete,
		OnSpawn,
		OnDie,
		OnKill,
		OnChampionDie,
		OnChampionLevelUp,
		OnChampionKillPre,
		OnChampionKill,
		OnChampionKillPost,
		OnChampionSingleKill,
		OnChampionDoubleKill,
		OnChampionTripleKill,
		OnChampionQuadraKill,
		OnChampionPentaKill,
		OnChampionUnrealKill,
		OnFirstBlood,
		OnDamageTaken,
		OnDamageGiven,
		OnSpellCast1,
		OnSpellCast2,
		OnSpellCast3,
		OnSpellCast4,
		OnSpellAvatarCast1,
		OnSpellAvatarCast2,
		OnGoldSpent,
		OnGoldEarned,
		OnItemConsumeablePurchased,
		OnCriticalStrike,
		OnAce,
		OnReincarnate,
		OnChangeChampion,
		OnDampenerKill,
		OnDampenerDie,
		OnDampenerRespawnSoon,
		OnDampenerRespawn,
		OnDampenerDamage,
		OnTurretKill,
		OnTurretDie,
		OnTurretDamage,
		OnMinionKill,
		OnMinionDenied,
		OnNeutralMinionKill,
		OnSuperMonsterKill,
		OnAcquireRedBuffFromNeutral,
		OnAcquireBlueBuffFromNeutral,
		OnHQKill,
		OnHQDie,
		OnHeal,
		OnCastHeal,
		OnBuff,
		OnCrowdControlDealt,
		OnKillingSpree,
		OnKillingSpreeSet1,
		OnKillingSpreeSet2,
		OnKillingSpreeSet3,
		OnKillingSpreeSet4,
		OnKillingSpreeSet5,
		OnKillingSpreeSet6,
		OnKilledUnitOnKillingSpree,
		OnKilledUnitOnKillingSpreeSet1,
		OnKilledUnitOnKillingSpreeSet2,
		OnKilledUnitOnKillingSpreeSet3,
		OnKilledUnitOnKillingSpreeSet4,
		OnKilledUnitOnKillingSpreeSet5,
		OnKilledUnitOnKillingSpreeSet6,
		OnKilledUnitOnKillingSpreeDoubleKill,
		OnKilledUnitOnKillingSpreeTripleKill,
		OnKilledUnitOnKillingSpreeQuadraKill,
		OnKilledUnitOnKillingSpreePentaKill,
		OnKilledUnitOnKillingSpreeUnrealKill,
		OnDeathAssist,
		OnQuit,
		OnLeave,
		OnReconnect,
		OnGameStart,
		OnAssistingSpreeSet1,
		OnAssistingSpreeSet2,
		OnChampionTripleAssist,
		OnChampionPentaAssist,
		OnPing,
		OnPingPlayer,
		OnPingBuilding,
		OnPingOther,
		OnEndGame,
		OnSpellLevelup1,
		OnSpellLevelup2,
		OnSpellLevelup3,
		OnSpellLevelup4,
		OnSpellEvolve1,
		OnSpellEvolve2,
		OnSpellEvolve3,
		OnSpellEvolve4,
		OnItemPurchased,
		OnItemSold,
		OnItemRemoved,
		OnItemUndo,
		OnItemCallout,
		OnItemGroupChange,
		OnItemChange,
		OnUndoEnabledChange,
		OnShopItemSubstitutionChange,
		OnShopMenuOpen,
		OnShopMenuClose,
		OnSurrenderVoteStart,
		OnSurrenderVote,
		OnSurrenderVoteAlready,
		OnSurrenderFailedVotes,
		OnSurrenderTooEarly,
		OnSurrenderAgreed,
		OnSurrenderSpam,
		OnSurrenderEarlyAllowed,
		OnEqualizeVoteStart,
		OnEqualizeVote,
		OnEqualizeVoteAlready,
		OnEqualizeFailedVotes,
		OnEqualizeTooEarly,
		OnEqualizeNotEnoughGold,
		OnEqualizeNotEnoughLevels,
		OnEqualizeAgreed,
		OnEqualizeSpam,
		OnPause,
		OnPauseResume,
		OnMinionsSpawn,
		OnStartGameMessage1,
		OnStartGameMessage2,
		OnStartGameMessage3,
		OnStartGameMessage4,
		OnStartGameMessage5,
		OnAlert,
		OnScoreboardOpen,
		OnAudioEventFinished,
		OnNexusCrystalStart,
		OnCapturePointNeutralized_A,
		OnCapturePointNeutralized_B,
		OnCapturePointNeutralized_C,
		OnCapturePointNeutralized_D,
		OnCapturePointNeutralized_E,
		OnCapturePointCaptured_A,
		OnCapturePointCaptured_B,
		OnCapturePointCaptured_C,
		OnCapturePointCaptured_D,
		OnCapturePointCaptured_E,
		OnCapturePointFiveCap,
		OnVictoryPointThreshold1,
		OnVictoryPointThreshold2,
		OnVictoryPointThreshold3,
		OnVictoryPointThreshold4,
		OnMinionKillVictoryThreshold1,
		OnMinionKillVictoryThreshold2,
		OnTurretKillVictoryThreshold1,
		OnTurretKillVictoryThreshold2,
		OnReplayFastForwardStart,
		OnReplayFastForwardEnd,
		OnReplayOnKeyframeFinished,
		OnReplayDestroyAllObjects,
		OnKillDragon,
		OnKillDragon_Spectator,
		OnKillDragonSteal,
		OnKillWorm,
		OnKillWorm_Spectator,
		OnKillWormSteal,
		OnKillSpiderBoss,
		OnKillSpiderBoss_Spectator,
		OnCaptureAltar,
		OnCaptureAltar_Spectator,
		OnPlaceWard,
		OnKillWard,
		OnMinionAscended,
		OnChampionAscended,
		OnClearAscended,
		OnGameStatEvent,
		OnRelativeTeamColorChange
	};

	public enum class GameMapId
	{
        CrystalScar = 8,
        TwistedTreeline = 10,
        SummonersRift,
        HowlingAbyss
	};

	public enum class PingType
	{
		Normal = 1,
		Fallback = 5,
		EnemyMissing = 3,
		Danger = 2,
		OnMyWay = 4,
		AssistMe = 6,
	};

	public enum class MasteryPage
	{
		Offense = 116,
		Defense,
		Utility,
		Ferocity = 148,
		Resolve,
		Cunning
	};

	public enum class ItemId
	{
		Unknown = 0,
		Abyssal_Scepter = 3001,
		Aegis_of_the_Legion = 3105,
		Aether_Wisp = 3113,
		Amplifying_Tome = 1052,
		Ancient_Coin = 3301,
		Archangels_Staff = 3003,
		Archangels_Staff_Crystal_Scar = 3007,
		Ardent_Censer = 3504,
		Athenes_Unholy_Grail = 3174,
		B_F_Sword = 1038,
		Bamis_Cinder = 3751,
		Banner_of_Command = 3060,
		Banshees_Veil = 3102,
		Berserkers_Greaves = 3006,
		Berserkers_Greaves_Enchantment_Alacrity = 1301,
		Berserkers_Greaves_Enchantment_Captain = 1302,
		Berserkers_Greaves_Enchantment_Distortion = 1303,
		Berserkers_Greaves_Enchantment_Furor = 1300,
		Bilgewater_Cutlass = 3144,
		Blade_of_the_Ruined_King = 3153,
		Blasting_Wand = 1026,
		Boots_of_Mobility = 3117,
		Boots_of_Mobility_Enchantment_Alacrity = 1326,
		Boots_of_Mobility_Enchantment_Captain = 1327,
		Boots_of_Mobility_Enchantment_Distortion = 1328,
		Boots_of_Mobility_Enchantment_Furor = 1325,
		Boots_of_Speed = 1001,
		Boots_of_Swiftness = 3009,
		Boots_of_Swiftness_Enchantment_Alacrity = 1306,
		Boots_of_Swiftness_Enchantment_Captain = 1307,
		Boots_of_Swiftness_Enchantment_Distortion = 1308,
		Boots_of_Swiftness_Enchantment_Furor = 1305,
		Brawlers_Gloves = 1051,
		Catalyst_the_Protector = 3010,
		Caulfields_Warhammer = 3133,
		Chain_Vest = 1031,
		Chalice_of_Harmony = 3028,
		Cloak_of_Agility = 1018,
		Cloth_Armor = 1029,
		Corrupting_Potion = 2033,
		Crystalline_Bracer = 3801,
		Cull = 1083,
		Dagger = 1042,
		Dead_Mans_Plate = 3742,
		Deaths_Dance = 3812,
		Deaths_Daughter = 3902,
		Dervish_Blade = 3137,
		Diet_Poro_Snax = 2054,
		Dorans_Blade = 1055,
		Dorans_Ring = 1056,
		Dorans_Shield = 1054,
		Duskblade_of_Draktharr = 3147,
		Elixir_of_Iron = 2138,
		Elixir_of_Sorcery = 2139,
		Elixir_of_Wrath = 2140,
		Entropy = 3184,
		Essence_Reaver = 3508,
		Executioners_Calling = 3123,
		Explorers_Ward = 2050,
		Eye_of_the_Equinox = 2303,
		Eye_of_the_Oasis = 2302,
		Eye_of_the_Watchers = 2301,
		Face_of_the_Mountain = 3401,
		Faerie_Charm = 1004,
		Farsight_Alteration = 3363,
		Fiendish_Codex = 3108,
		Fire_at_Will = 3901,
		Forbidden_Idol = 3114,
		Frost_Queens_Claim = 3092,
		Frostfang = 3098,
		Frozen_Heart = 3110,
		Frozen_Mallet = 3022,
		Giant_Slayer = 3034,
		Giants_Belt = 1011,
		Glacial_Shroud = 3024,
		Golden_Transcendence = 3460,
		Golden_Transcendence_Disabled = 3461,
		Greater_Stealth_Totem_Trinket = 3361,
		Greater_Vision_Totem_Trinket = 3362,
		Guardian_Angel = 3026,
		Guardians_Horn = 2051,
		Guinsoos_Rageblade = 3124,
		Haunting_Guise = 3136,
		Health_Potion = 2003,
		Hexdrinker = 3155,
		Hextech_Gunblade = 3146,
		Hextech_Revolver = 3145,
		Hextech_Sweeper = 3348,
		Hunters_Machete = 1041,
		Hunters_Potion = 2032,
		Hunters_Talisman = 1039,
		Iceborn_Gauntlet = 3025,
		Infinity_Edge = 3031,
		Ionian_Boots_of_Lucidity = 3158,
		Ionian_Boots_of_Lucidity_Enchantment_Alacrity = 1331,
		Ionian_Boots_of_Lucidity_Enchantment_Captain = 1332,
		Ionian_Boots_of_Lucidity_Enchantment_Distortion = 1333,
		Ionian_Boots_of_Lucidity_Enchantment_Furor = 1330,
		Jaurims_Fist = 3052,
		Kindlegem = 3067,
		Kircheis_Shard = 2015,
		Last_Whisper = 3035,
		Liandrys_Torment = 3151,
		Lich_Bane = 3100,
		Locket_of_the_Iron_Solari = 3190,
		Long_Sword = 1036,
		Lord_Dominiks_Regards = 3036,
		Lord_Van_Damms_Pillager = 3104,
		Ludens_Echo = 3285,
		Manamune = 3004,
		Manamune_Crystal_Scar = 3008,
		Maw_of_Malmortius = 3156,
		Mejais_Soulstealer = 3041,
		Mercurial_Scimitar = 3139,
		Mercurys_Treads = 3111,
		Mercurys_Treads_Enchantment_Alacrity = 1321,
		Mercurys_Treads_Enchantment_Captain = 1322,
		Mercurys_Treads_Enchantment_Distortion = 1323,
		Mercurys_Treads_Enchantment_Furor = 1320,
		Mikaels_Crucible = 3222,
		Moonflair_Spellblade = 3170,
		Morellonomicon = 3165,
		Mortal_Reminder = 3033,
		Muramana = 3043,
		Nashors_Tooth = 3115,
		Needlessly_Large_Rod = 1058,
		Negatron_Cloak = 1057,
		Ninja_Tabi = 3047,
		Ninja_Tabi_Enchantment_Alacrity = 1316,
		Ninja_Tabi_Enchantment_Captain = 1317,
		Ninja_Tabi_Enchantment_Distortion = 1318,
		Ninja_Tabi_Enchantment_Furor = 1315,
		Nomads_Medallion = 3096,
		Null_Magic_Mantle = 1033,
		Odyns_Veil = 3180,
		Ohmwrecker = 3056,
		Oracle_Alteration = 3364,
		Oracles_Extract = 2047,
		Orb_of_Winter = 3112,
		Overlords_Bloodmail = 3084,
		Perfect_Hex_Core = 3198,
		Phage = 3044,
		Phantom_Dancer = 3046,
		Pickaxe = 1037,
		Poro_Snax = 2052,
		Prospectors_Blade = 1062,
		Prospectors_Ring = 1063,
		Prototype_Hex_Core = 3200,
		Quicksilver_Sash = 3140,
		Rabadons_Deathcap = 3089,
		Raise_Morale = 3903,
		Randuins_Omen = 3143,
		Rapid_Firecannon = 3094,
		Raptor_Cloak = 2053,
		Ravenous_Hydra = 3074,
		Ravenous_Hydra_Melee_Only = 3074,
		Recurve_Bow = 1043,
		Refillable_Potion = 2031,
		Rejuvenation_Bead = 1006,
		Relic_Shield = 3302,
		Righteous_Glory = 3800,
		Rod_of_Ages = 3027,
		Rod_of_Ages_Crystal_Scar = 3029,
		Ruby_Crystal = 1028,
		Ruby_Sightstone = 2045,
		Runaans_Hurricane = 3085,
		Runaans_Hurricane_Ranged_Only = 3085,
		Rylais_Crystal_Scepter = 3116,
		Sanguine_Blade = 3181,
		Sapphire_Crystal = 1027,
		Seekers_Armguard = 3191,
		Seraphs_Embrace = 3048,
		Serrated_Dirk = 3134,
		Sheen = 3057,
		Sightstone = 2049,
		Skirmishers_Sabre = 3715,
		Skirmishers_Sabre_Enchantment_Cinderhulk = 1413,
		Skirmishers_Sabre_Enchantment_Devourer = 1415,
		Skirmishers_Sabre_Enchantment_Runic_Echoes = 1414,
		Skirmishers_Sabre_Enchantment_Sated_Devourer = 3931,
		Skirmishers_Sabre_Enchantment_Warrior = 1412,
		Sorcerers_Shoes = 3020,
		Sorcerers_Shoes_Enchantment_Alacrity = 1311,
		Sorcerers_Shoes_Enchantment_Captain = 1312,
		Sorcerers_Shoes_Enchantment_Distortion = 1313,
		Sorcerers_Shoes_Enchantment_Furor = 1310,
		Soul_Anchor_Trinket = 3345,
		Spectres_Cowl = 3211,
		Spellthiefs_Edge = 3303,
		Spirit_Visage = 3065,
		Stalkers_Blade = 3706,
		Stalkers_Blade_Enchantment_Cinderhulk = 1401,
		Stalkers_Blade_Enchantment_Devourer = 1403,
		Stalkers_Blade_Enchantment_Runic_Echoes = 1402,
		Stalkers_Blade_Enchantment_Sated_Devourer = 3930,
		Stalkers_Blade_Enchantment_Warrior = 1400,
		Statikk_Shiv = 3087,
		Steraks_Gage = 3053,
		Stinger = 3101,
		Sunfire_Cape = 3068,
		Sweeping_Lens_Trinket = 3341,
		Talisman_of_Ascension = 3069,
		Targons_Brace = 3097,
		Tear_of_the_Goddess = 3070,
		Tear_of_the_Goddess_Crystal_Scar = 3073,
		The_Black_Cleaver = 3071,
		The_Black_Spear = 3599,
		The_Bloodthirster = 3072,
		The_Dark_Seal = 1082,
		The_Hex_Core_mk_1 = 3196,
		The_Hex_Core_mk_2 = 3197,
		The_Lightbringer = 3185,
		Thornmail = 3075,
		Tiamat = 3077,
		Tiamat_Melee_Only = 3077,
		Titanic_Hydra = 3748,
		Total_Biscuit_of_Rejuvenation = 2010,
		Trackers_Knife = 3711,
		Trackers_Knife_Enchantment_Cinderhulk = 1409,
		Trackers_Knife_Enchantment_Devourer = 1411,
		Trackers_Knife_Enchantment_Runic_Echoes = 1410,
		Trackers_Knife_Enchantment_Sated_Devourer = 3932,
		Trackers_Knife_Enchantment_Warrior = 1408,
		Trinity_Force = 3078,
		Vampiric_Scepter = 1053,
		Vision_Ward = 2043,
		Void_Staff = 3135,
		Wardens_Mail = 3082,
		Warding_Totem_Trinket = 3340,
		Warmogs_Armor = 3083,
		Wicked_Hatchet = 3122,
		Will_of_the_Ancients = 3152,
		Wits_End = 3091,
		Wooglets_Witchcap = 3090,
		Youmuus_Ghostblade = 3142,
		Zeal = 3086,
		Zekes_Harbinger = 3050,
		Zhonyas_Hourglass = 3157,
		ZzRot_Portal = 3512,
	};

	public enum class Emote
	{
		Dance = 0,
		Taunt,
		Laugh,
		Joke,
		Toggle
	};

	public enum class DamageHitType
	{
		Invulnerable,
		Dodge = 2,
		Critical,
		Normal,
		Miss
	};

	public enum class DamageType
	{
		Physical,
		Magical,
		True,
		Mixed
	};

	public enum class HudDrawingType
	{
		Healthbar,
		Menu,
		PwHud,
		Minimap,
		Ping
	};

	public enum class HudDrawingObject
	{
		TacticalMap
	};

	public enum class PingCategory
	{
		Normal,
		Danger = 2,
		EnemyMissing,
		OnMyWay,
		Fallback,
		AssistMe
	};

	public enum class Champion
	{
		Aatrox,
		Ahri,
		Akali,
		Alistar,
		Amumu,
		Anivia,
		Annie,
		Ashe,
		Azir,
		Bard,
		Blitzcrank,
		Brand,
		Braum,
		Caitlyn,
		Cassiopeia,
		Chogath,
		Corki,
		Darius,
		Diana,
		DrMundo,
		Draven,
		Ekko,
		Elise,
		Evelynn,
		Ezreal,
		FiddleSticks,
		Fiora,
		Fizz,
		Galio,
		Gangplank,
		Garen,
		Gnar,
		Gragas,
		Graves,
		Hecarim,
		Heimerdinger,
		Illaoi,
		Irelia,
		Janna,
		JarvanIV,
		Jax,
		Jayce,
		Jhin,
		Jinx,
		Kalista,
		Karma,
		Karthus,
		Kassadin,
		Katarina,
		Kayle,
		Kennen,
		Khazix,
		Kindred,
		KogMaw,
		Leblanc,
		LeeSin,
		Leona,
		Lissandra,
		Lucian,
		Lulu,
		Lux,
		Malphite,
		Malzahar,
		Maokai,
		MasterYi,
		MissFortune,
		Mordekaiser,
		Morgana,
		Nami,
		Nasus,
		Nautilus,
		Nidalee,
		Nocturne,
		Nunu,
		Olaf,
		Orianna,
		Pantheon,
		Poppy,
		Quinn,
		Rammus,
		RekSai,
		Renekton,
		Rengar,
		Riven,
		Rumble,
		Ryze,
		Sejuani,
		Shaco,
		Shen,
		Shyvana,
		Singed,
		Sion,
		Sivir,
		Skarner,
		Sona,
		Soraka,
		Swain,
		Syndra,
		TahmKench,
		Talon,
		Taric,
		Teemo,
		Thresh,
		Tristana,
		Trundle,
		Tryndamere,
		TwistedFate,
		Twitch,
		Udyr,
		Urgot,
		Varus,
		Vayne,
		Veigar,
		Velkoz,
		Vi,
		Viktor,
		Vladimir,
		Volibear,
		Warwick,
		MonkeyKing,
		Xerath,
		XinZhao,
		Yasuo,
		Yorick,
		Zac,
		Zed,
		Ziggs,
		Zilean,
		Zyra,
		Unknown = -1
	};

	public enum class ClickType
	{
		Attack,
		Move
	};

	public enum class DampenerState
	{
		Unknown = -1,
		Alive,
		Destroyed
	};

	public enum class SurrenderVoteType
	{
		Yes = 1,
		No = 2,
	};

	public enum class PacketCallbackType
	{
		Send,
		Receive,
		BothWays
	};
}