<ips:template parameters="$html, $title=NULL" />
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>{$title}</title>
		<link rel='stylesheet' href='css/reset.css' media='all'>
		<link rel='stylesheet' href='css/fonts.css' media='all'>
		<link rel='stylesheet' href='css/global.css' media='all'>
		<link rel='stylesheet' href='css/layout.css' media='all'>
		<link rel='stylesheet' href='css/messages.css' media='all'>
		<link rel='stylesheet' href='css/misc.css' media='all'>
		<link rel='stylesheet' href='css/forms.css' media='all'>
		<link rel='stylesheet' href='css/typography.css' media='all'>
		<link rel='stylesheet' href='css/buttons.css' media='all'>
		<link rel='stylesheet' href='css/installer.css' media='all'>
		<script type="text/javascript">
			var IPS_TIMEOUT = 30;
		</script>
		<script src="js/jquery.min.js"></script>
		<script src="js/multipleRedirect.js"></script>
	</head>
	<body class="ipsApp ipsApp_front ipsJS_none ipsClearfix ipsLayout_noBackground">
		{$html|raw}
	</body>
</html>