<ips:template parameters="$url, $message" />
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>{lang="redirecting"}</title>
		<link rel='stylesheet' href='css/reset.css' media='all'>
		<link rel='stylesheet' href='css/fonts.css' media='all'>
		<link rel='stylesheet' href='css/global.css' media='all'>
		<link rel='stylesheet' href='css/layout.css' media='all'>
		<link rel='stylesheet' href='css/messages.css' media='all'>
		<link rel='stylesheet' href='css/misc.css' media='all'>
		<link rel='stylesheet' href='css/forms.css' media='all'>
		<link rel='stylesheet' href='css/typography.css' media='all'>
		<link rel='stylesheet' href='css/buttons.css' media='all'>
		<link rel='stylesheet' href='css/installer.css' media='all'>
		<meta http-equiv="refresh" content="2; url={$url}" />
	</head>
	<body>
		<p class="ipsMessage ipsMessage_info ipsRedirectMessage">
			<strong>{lang="$message"}</strong><br />
			<br />
			{lang="redirecting_wait"}
		</p>
	</body>
</html>